### ISSUE TITLE
[Bug] Storage device without smart support causes crash

### ISSUE THREAD

**Issue by Novocaine85** [tomaae/homeassistant-openmediavault#10] opened 2020-05-11 11:48 UTC
## Describe the issue

I'm unable to get any entity from home assistant. OMV is on a different machine. After filling all the requested information, (use SSL and Verify SSL are unchecked since ATM i do not have ssl certificate on this machine) i get some errors on log. please check below.

## How to reproduce the issue

- Install addon from HACS
- Set up the addon with the correct informations (ip, username, password, SSL options both unchecked)
- After receiving the message that the addon has been configured, devices or entities are not shown on the OMV addon box
- Check error log, error found like above.

## Expected behavior

No errors in log, plugin showing server entities. 

## Screenshots

![image](https://user-images.githubusercontent.com/7164237/81558216-981e0f00-938d-11ea-83c4-5161f61e2cca.png)

## Software versions

 - Home Assistant version: 0.109.6
 - openmediavault integration version: 1.1.0
 - openmediavault software version: 5.4.5-1 (Ususl)

## Traceback/Error logs
Log Details (WARNING)
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 1:31:47 PM (1 occurrences)
Last logged: 1:31:47 PM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for openmediavault doing I/O at custom_components/openmediavault/omv_api.py, line 140: verify=self._ssl_verify,

------------------------------------------------------------------
Logger: homeassistant.config_entries
Source: custom_components/openmediavault/helper.py:15
First occurred: 1:31:50 PM (1 occurrences)
Last logged: 1:31:50 PM

Error setting up entry OMV for openmediavault
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 216, in async_setup
    hass, self
  File "/config/custom_components/openmediavault/__init__.py", line 31, in async_setup_entry
    await controller.async_hwinfo_update()
  File "/config/custom_components/openmediavault/omv_controller.py", line 116, in async_hwinfo_update
    await self.hass.async_add_executor_job(self.get_disk)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/openmediavault/omv_controller.py", line 233, in get_disk
    {"name": "smartsupportis", "type": "bool", "default": False},
  File "/config/custom_components/openmediavault/helper.py", line 86, in parse_api
    data = fill_vals(data, entry, uid, vals)
  File "/config/custom_components/openmediavault/helper.py", line 225, in fill_vals
    data[_name] = from_entry(entry, _source, default=_default)
  File "/config/custom_components/openmediavault/helper.py", line 15, in from_entry
    if param not in entry:
TypeError: argument of type 'NoneType' is not iterable

Thank you

**Comment by tomaae** [comment] 2020-05-11 12:38
Detected I/O inside the event loop is not related, thats just connectivity check inside config flow.
You are getting a crash during physical disk detection. Can you debug it?

**Comment by Novocaine85** [comment] 2020-05-11 13:05
2020-05-11 14:53:02 DEBUG (SyncWorker_13) [custom_components.openmediavault.omv_api] OpenMediaVault 192.168.178.71 query response: {'response': [{'devicename': 'mmcblk0', 'canonicaldevicefile': '/dev/mmcblk0', 'devicefile': '/dev/disk/by-id/mmc-SD32G_0x88a0e8a5', 'devicelinks': ['/dev/disk/by-id/mmc-SD32G_0x88a0e8a5', '/dev/disk/by-path/platform-fe340000.emmc2'], 'model': '', 'size': '31104958464', 'description': 'n/a [/dev/mmcblk0, 28.96 GiB]', 'vendor': '', 'serialnumber': '', 'israid': False, 'isroot': False}, {'devicename': 'sda', 'canonicaldevicefile': '/dev/sda', 'devicefile': '/dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N6TEKSHU', 'devicelinks': ['/dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N6TEKSHU', '/dev/disk/by-id/wwn-0x50014ee2b6c6ebef', '/dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1:1.0-scsi-0:0:0:0'], 'model': 'EFRX-68EUZN0', 'size': '3000592982016', 'description': 'EFRX-68EUZN0 [/dev/sda, 2.72 TiB]', 'vendor': 'WDC WD30', 'serialnumber': 'WD-WCC4N6TEKSHU', 'israid': False, 'isroot': False}, {'devicename': 'sdb', 'canonicaldevicefile': '/dev/sdb', 'devicefile': '/dev/disk/by-id/usb-KingDian_S400_120GB_000000123AE3-0:0', 'devicelinks': ['/dev/disk/by-id/usb-KingDian_S400_120GB_000000123AE3-0:0', '/dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:2:1.0-scsi-0:0:0:0'], 'model': 'S400 120GB', 'size': '120034123776', 'description': 'S400 120GB [/dev/sdb, 111.79 GiB]', 'vendor': 'KingDian', 'serialnumber': '000000123AE3', 'israid': False, 'isroot': True}], 'error': None}
2020-05-11 14:53:02 DEBUG (SyncWorker_13) [custom_components.openmediavault.helper] Processing source [{'devicename': 'mmcblk0', 'canonicaldevicefile': '/dev/mmcblk0', 'devicefile': '/dev/disk/by-id/mmc-SD32G_0x88a0e8a5', 'devicelinks': ['/dev/disk/by-id/mmc-SD32G_0x88a0e8a5', '/dev/disk/by-path/platform-fe340000.emmc2'], 'model': '', 'size': '31104958464', 'description': 'n/a [/dev/mmcblk0, 28.96 GiB]', 'vendor': '', 'serialnumber': '', 'israid': False, 'isroot': False}, {'devicename': 'sda', 'canonicaldevicefile': '/dev/sda', 'devicefile': '/dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N6TEKSHU', 'devicelinks': ['/dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N6TEKSHU', '/dev/disk/by-id/wwn-0x50014ee2b6c6ebef', '/dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1:1.0-scsi-0:0:0:0'], 'model': 'EFRX-68EUZN0', 'size': '3000592982016', 'description': 'EFRX-68EUZN0 [/dev/sda, 2.72 TiB]', 'vendor': 'WDC WD30', 'serialnumber': 'WD-WCC4N6TEKSHU', 'israid': False, 'isroot': False}, {'devicename': 'sdb', 'canonicaldevicefile': '/dev/sdb', 'devicefile': '/dev/disk/by-id/usb-KingDian_S400_120GB_000000123AE3-0:0', 'devicelinks': ['/dev/disk/by-id/usb-KingDian_S400_120GB_000000123AE3-0:0', '/dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:2:1.0-scsi-0:0:0:0'], 'model': 'S400 120GB', 'size': '120034123776', 'description': 'S400 120GB [/dev/sdb, 111.79 GiB]', 'vendor': 'KingDian', 'serialnumber': '000000123AE3', 'israid': False, 'isroot': True}]
2020-05-11 14:53:02 DEBUG (SyncWorker_13) [custom_components.openmediavault.helper] Processing entry {'devicename': 'mmcblk0', 'canonicaldevicefile': '/dev/mmcblk0', 'devicefile': '/dev/disk/by-id/mmc-SD32G_0x88a0e8a5', 'devicelinks': ['/dev/disk/by-id/mmc-SD32G_0x88a0e8a5', '/dev/disk/by-path/platform-fe340000.emmc2'], 'model': '', 'size': '31104958464', 'description': 'n/a [/dev/mmcblk0, 28.96 GiB]', 'vendor': '', 'serialnumber': '', 'israid': False, 'isroot': False}
2020-05-11 14:53:02 INFO (SyncWorker_0) [homeassistant.loader] Loaded climate from homeassistant.components.climate
2020-05-11 14:53:02 DEBUG (SyncWorker_13) [custom_components.openmediavault.helper] Processing entry {'devicename': 'sda', 'canonicaldevicefile': '/dev/sda', 'devicefile': '/dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N6TEKSHU', 'devicelinks': ['/dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N6TEKSHU', '/dev/disk/by-id/wwn-0x50014ee2b6c6ebef', '/dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1:1.0-scsi-0:0:0:0'], 'model': 'EFRX-68EUZN0', 'size': '3000592982016', 'description': 'EFRX-68EUZN0 [/dev/sda, 2.72 TiB]', 'vendor': 'WDC WD30', 'serialnumber': 'WD-WCC4N6TEKSHU', 'israid': False, 'isroot': False}
2020-05-11 14:53:02 DEBUG (SyncWorker_13) [custom_components.openmediavault.helper] Processing entry {'devicename': 'sdb', 'canonicaldevicefile': '/dev/sdb', 'devicefile': '/dev/disk/by-id/usb-KingDian_S400_120GB_000000123AE3-0:0', 'devicelinks': ['/dev/disk/by-id/usb-KingDian_S400_120GB_000000123AE3-0:0', '/dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:2:1.0-scsi-0:0:0:0'], 'model': 'S400 120GB', 'size': '120034123776', 'description': 'S400 120GB [/dev/sdb, 111.79 GiB]', 'vendor': 'KingDian', 'serialnumber': '000000123AE3', 'israid': False, 'isroot': True}
2020-05-11 14:53:02 DEBUG (SyncWorker_13) [custom_components.openmediavault.omv_api] OpenMediaVault 192.168.178.71 query: Smart, getInformation, {'devicefile': '/dev/mmcblk0'}, {'updatelastaccess': False}
2020-05-11 14:53:02 INFO (MainThread) [homeassistant.setup] Setting up zeroconf
2020-05-11 14:53:02 DEBUG (SyncWorker_13) [custom_components.openmediavault.omv_api] OpenMediaVault 192.168.178.71 query response: {'response': None, 'error': {'code': 0, 'message': "Device '/dev/mmcblk0' does not support S.M.A.R.T.", 'trace': "OMV\\AssertException: Device '/dev/mmcblk0' does not support S.M.A.R.T. in /usr/share/php/openmediavault/system/storage/storagedevice.inc:214\nStack trace:\n#0 /usr/share/openmediavault/engined/rpc/smart.inc(423): OMV\\System\\Storage\\StorageDevice->assertHasSmartSupport()\n#1 [internal function]: Engined\\Rpc\\Smart->getInformation(Array, Array)\n#2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)\n#3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\\Rpc\\ServiceAbstract->callMethod('getInformation', Array, Array)\n#4 /usr/sbin/omv-engined(537): OMV\\Rpc\\Rpc::call('Smart', 'getInformation', Array, Array, 1)\n#5 {main}"}}
2020-05-11 14:53:02 DEBUG (SyncWorker_13) [custom_components.openmediavault.helper] Processing source [None]
2020-05-11 14:53:02 DEBUG (SyncWorker_13) [custom_components.openmediavault.helper] Processing entry None

**Comment by tomaae** [comment] 2020-05-11 15:47
I see, there is an MMC card which is causing issues. I should have a reader and a card somewhere, so it should not be a problem to fix.

**Comment by tomaae** [comment] 2020-05-19 18:31
So, I was not able to able to reproduce on my server by connecting a card reader with a card.
I managed to get old pi2, so I should be able to replicate the issue now and solve it soon.

**Comment by ttaidapos** [comment] 2020-05-19 18:35
> So, I was not able to able to reproduce on my server by connecting a card reader with a card.
> I managed to get old pi2, so I should be able to replicate the issue now and solve it soon.

Cool let me know if you need any other info! :)

**Comment by tomaae** [comment] 2020-05-19 19:21
Installation took 2 hours on poor pi2, but I finally got this error reproduced. So all good.

**Comment by tomaae** [comment] 2020-05-19 19:53
That was a simple fix once I got it reproduced.
Fix released in v1.1.1

**Comment by LanceMcCarthy** [comment] 2020-05-21 00:26
Looks like the last update fixed it:

![image](https://user-images.githubusercontent.com/3520532/82510251-2013bf80-9ad8-11ea-9546-5edbfc799e47.png)

Nice work!

**Comment by tomaae** [comment] 2020-05-21 03:10
perfect.
are those internal 1 and internal 2 correct names?

**Comment by LanceMcCarthy** [comment] 2020-05-21 11:22
> perfect.
> are those internal 1 and internal 2 correct names?

Correct. Although I use a slightly more readable display name for the HA gauge card, here's the Labels list from OMV directly:

![image](https://user-images.githubusercontent.com/3520532/82554310-ac9f9b80-9b33-11ea-8ead-23b4a95b4b35.png)

**Comment by tomaae** [comment] 2020-05-21 15:25
Thats perfectly fine then, I just wanted to make sure :)

**Closed** 2020-05-29 01:43 UTC
Labels: bug, testing
