### ISSUE TITLE
After upgrade of Home Assistant Core to latest version integration stopped working

### ISSUE THREAD

**Issue by bgug777** [tomaae/homeassistant-openmediavault#134] opened 2023-09-06 22:40 UTC
## Describe the issue
After upgrade of Home Assistant Core to latest version integration stopped working.
Deleted my OMV entry in HA and recreated it but no entities were discovered/added.

## Software versions
 - Home Assistant version: 
Home Assistant 2023.9.0
Supervisor 2023.08.3
Operating System 10.5
Frontend 20230906.1 - latest

 - openmediavault integration version: v1.4.1
 
 - openmediavault software version: 6.8.0-1 (Shaitan) - Linux 6.1.21-v8+

[logs.txt](https://github.com/tomaae/homeassistant-openmediavault/files/12543041/logs.txt)

**Comment by BebeMischa** [comment] 2023-09-07 05:34
Confirm. Also here all stopped. After remove and add the integration again it initializes, logs in and closes the setup as completed. But no new entities are made.

**Comment by DieMetRik** [comment] 2023-09-07 08:59
Confirm. Stop working

**Comment by Andy1910** [comment] 2023-09-07 09:56
same here rolled back to 2023.8.4 back working again

**Comment by vvrockhound** [comment] 2023-09-07 16:08
same here - no entities

**Comment by rdrosa** [comment] 2023-09-07 19:00
same here, no entities after upgrade

**Comment by J-D-Torres** [comment] 2023-09-07 21:56
Same same

**Comment by tomaae** [comment] 2023-09-08 05:38
yup, many integrations broke. that sneaky breaking change messed up a lot.

**Comment by BebeMischa** [comment] 2023-09-12 14:46
So, how can we help?

**Comment by tomaae** [comment] 2023-09-12 18:34
no help needed with this one, just need time to update all my integrations

**Comment by FelixDelGato** [comment] 2023-09-17 02:09
Getting to be a rough update month. My OMV is also broken now along with Chamberlain garage opener. That one is a bit inconvenient. Well... guess I'd complain if I was paying for HA but... considering that's it's open source and I've only donated to them... I'll be patient lol. I suspect they are working on it.
I work in a field where software updates (patching) is extremely common. I work most weekends patching customers servers. I get... sometimes things get a bit wonky. All hell breaks lose and customers get pretty irate... as they should. Spending a lot of big dollars on a product they dont just use but have SLAs or even laws if calls aren't monitored. This is just home automation. Life will go on...no one will die and no one will get fined thousands of dollars so...hang in there folks. The team will sort it out as soon as they can. In the meantime...just log into the OMV portal lol. 
Still love ya HA team! Keep doing what you do. Been wanting a automated home since the first time read about it so long ago..I can't remember when. Now I have it... it's very inexpensive and best of... I'm not forced into some megscorps box and cloud and all that goes along with it. Cheers!

**Comment by FelixDelGato** [comment] 2023-09-17 02:14
> same here rolled back to 2023.8.4 back working again

Andy...did you rollback to core 8.4? And...are you just restoring a back up?

**Comment by Andy1910** [comment] 2023-09-17 07:46
> > same here rolled back to 2023.8.4 back working again
> 
> Andy...did you rollback to core 8.4? And...are you just restoring a back up?

just rolled back no backup involved

**Comment by tomaae** [comment] 2023-09-18 09:20
fixed in v1.4.2

**Closed by tomaae** 2023-09-18 09:20 UTC
Labels: bug

**Comment by FelixDelGato** [comment] 2023-09-18 17:48
Confirmed... working again. Well done! Now...just need Chamberlain Cover/garade door integration fixed.

**Comment by BebeMischa** [comment] 2023-09-18 17:51
confirmed, works again. Thank you very much @tomaae
